name: Unit Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - "*"
    schedule:
        -   cron: '0 0 * * *'

jobs:
    php-tests:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        env:
            COMPOSER_NO_INTERACTION: 1

        strategy:
            fail-fast: false
            matrix:
                php: [ 8.3, 8.2, 8.1 ]
                laravel: [ ^11, ^10, ^9 ]
                dependency-version: [ prefer-stable ]
                exclude:
                    -   laravel: ^10
                        php: 8.0
                    -   laravel: ^11
                        php: 8.0
                    -   laravel: ^11
                        php: 8.1

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: pcov
                    tools: composer:v2
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif

            -   name: Install dependencies
                run: |
                    composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
                    composer update --${{ matrix.dependency-version }} --prefer-dist --no-progress

            -   name: Execute Unit Tests
                run: vendor/bin/phpunit --coverage-text --coverage-clover=build/phpunit/logs/clover.xml

            -   name: "Send code coverage report to codecov.io"
                uses: "codecov/codecov-action@v4.0.2"
                with:
                    files: "build/phpunit/logs/clover.xml"
                    token: ${{ secrets.CODECOV_TOKEN }}
                    slug: AgelxNash/magicDto
